// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo_vxsRk3UYXHvjzjLawxWFUeqUmrFVB8',
    appId: '1:926214246132:web:526779026c1faacbf358a1',
    messagingSenderId: '926214246132',
    projectId: 'school-chat-app-f2175',
    authDomain: 'school-chat-app-f2175.firebaseapp.com',
    storageBucket: 'school-chat-app-f2175.appspot.com',
    measurementId: 'G-Z19ZDNP5S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXBdlttLtDldOn7ZvUseSPT4AZU2XARDg',
    appId: '1:926214246132:android:ecf150203bcde185f358a1',
    messagingSenderId: '926214246132',
    projectId: 'school-chat-app-f2175',
    storageBucket: 'school-chat-app-f2175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCx7-9Q8HYjIN_4Y83RJ0yfSBsqA1zzXc',
    appId: '1:926214246132:ios:0f40338d3da1a749f358a1',
    messagingSenderId: '926214246132',
    projectId: 'school-chat-app-f2175',
    storageBucket: 'school-chat-app-f2175.appspot.com',
    iosClientId: '926214246132-jdpobord1thiq815qtq4vbmfb24d4r5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCx7-9Q8HYjIN_4Y83RJ0yfSBsqA1zzXc',
    appId: '1:926214246132:ios:0f40338d3da1a749f358a1',
    messagingSenderId: '926214246132',
    projectId: 'school-chat-app-f2175',
    storageBucket: 'school-chat-app-f2175.appspot.com',
    iosClientId: '926214246132-jdpobord1thiq815qtq4vbmfb24d4r5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );
}
